### PR TITLE
Support multiple recipients in report email

### PR DESCRIPTION
**Pull request by mbrodala**
Allow "reportEmail" to be an array of email addresses to send the report email to multiple recipients.

### CODE REVIEW

**Comment by fsuter** [comment]
Nice idea, but if people set the "reportEmail" property via the Settings module, all they can do is enter a comma-separated list of addresses. So we should take this possibility into account, don't you think?

**Comment by mbrodala** [comment]
Good idea, I've taken this into account now.

**Comment by fsuter** [comment]
Thanks, that looks good.

I'll see what I can do in terms of release. I'm currently working on a new major version with support for TYPO3 11 (and removed support for TYPO3 9), so I don't know yet how this will fit in.

**Comment by mbrodala** [comment]
No worries, I'll add this as patch to our project in the meantime. :-)

**Comment by mbrodala** [comment]
Thanks. :slightly_smiling_face:

**Pull request merged**
