### PR TITLE
[TASK] Introduce Core-like testing with runTests.sh

### PR DESCRIPTION
**Pull request by linawolf**

### CODE REVIEW

**Comment by linawolf** [comment]
@fsuter Please have a look if this is the direction that you imagined. I will add unit and functional tests later on. I am not sure if we have to drop nimut first.

**Comment by fsuter** [comment]
Hi Lina. Thanks a lot for this huge work! Sorry for the late reply, I'm working only part-time these days.

For my understanding, I need to clarify a few things:

- why is it needed to have a .ddev configuration? Is the "make" command not enough? Are you supposed to execute "make" from inside the container?
- what's the "branch alias" introduced in the composer.json file? It does not correspond to an existing branch. External Import still uses "master" and there's no 7.2.x-dev branch. Is that coming from your fork?

As for the rest: 1) it's great to have this big code cleanup, 2) I don't understand all the details of the runTests.sh script, nor of the phpstan configuration, but I trust you on that.

**Comment by linawolf** [comment]
The ddev is not really needed and runTests.sh are executed in the docker containers provided by the script. I find it handy when debugging or instlalling stuff via composer as it comes with the correct PHP version. but I can exclude it locally from github.

The branch alias thingy allows me to require the current development version on dev-main as "^7.2.x-dev". This has the advantage I will notice once there is an official 7.2 Version and dev-main starts to develop for version 8.0 for example. The Core is doing it like this as well: 
https://github.com/TYPO3/typo3/blob/main/typo3/sysext/core/composer.json#L103
It is not strictly required but comes in handy. I can remove it if you would rather not maintain development versions here.

**Comment by fsuter** [comment]
Thanks for the explanations.

I would rather not have the DDEV configuration. As for the alias, I have never been that strict with branches. I used to created branches with funny names when starting new major versions, but this proved a hassle with the related extensions, so I'm, now just using "develop".

I forgot to answer one of your questions: for me it's ok to proceed with automated testing using `nimut/testing-framework` and change to `typo3/testing-framework` after the automation is in place.

**Comment by linawolf** [comment]
The branch-alias does not require any special naming requirements on branches. It is anlyzed by packagist whenever dev-main derived from your main branch is updated and will automatically make ^7.2.x-dev availible, without need for a a special branch or tag of that name. I can remove it if you want however.

**Comment by linawolf** [comment]
I removed the ddev configuration and added .ddev to the gitignore to document the desision.

**Comment by fsuter** [comment]
> The branch-alias does not require any special naming requirements on branches. It is anlyzed by packagist whenever dev-main derived from your main branch is updated and will automatically make ^7.2.x-dev availible, without need for a a special branch or tag of that name. I can remove it if you want however.

OK, that's fine then. But please note that I'm still using `master` and not `main`.

**Comment by linawolf** [comment]
Whatever default branch you have registered at packagist should be fine

**Comment by linawolf** [comment]
So are you ok with getting this merged? I have a 9 hour train ride today and could continue working on the functional tests...

**Comment by fsuter** [comment]
> So are you ok with getting this merged? I have a 9 hour train ride today and could continue working on the functional tests...

Yes, great, please proceed. Thanks a lot!

**Pull request merged**
